export const languageLabels = {
    az: 'آذربایجان دیلی',
    be: 'беларуская мова',
    bg: 'български',
    bs: 'босански',
    ca: 'Català',
    cs: 'Čeština',
    de: 'Deutsch',
    el: 'Greek',
    en: 'English',
    es: 'Español',
    et: 'Eesti keel',
    eu: 'Euskara',
    fa: 'فارسی',
    fi: 'Suomen kieli',
    fr: 'Français',
    gl: 'Galego',
    hu: 'Magyar',
    hr: 'Hrvatski',
    ja: '日本語',
    ko: '한국어',
    id: 'Bahasa Indonesia',
    it: 'Italiano',
    ml: 'മലയാളം',
    nb_NO: 'bokmål',
    nl: 'Nederlands',
    pl: 'Polski',
    pt: 'Português',
    pt_BR: 'Português (Brasil)',
    ro: 'limba română',
    ru: 'Русский',
    sk: 'slovenčina',
    sv: 'Svenska',
    ta: 'தமிழ்',
    tr: 'Türkçe',
    uk: 'украї́нська мо́ва',
    vi: 'tiếng Việt',
    zh_Hans: '简化字',
    zh_Hant: '漢語'
}
